// <auto-generated />
using System;
using AdminSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminSystem.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.MenuAggregate.Zmn_Ac_Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Affix");

                    b.Property<bool>("AlwaysShow");

                    b.Property<string>("DeepPath");

                    b.Property<bool>("IsDelete");

                    b.Property<bool>("IsVisible");

                    b.Property<int>("MenuFuntionType");

                    b.Property<string>("MenuIcon");

                    b.Property<string>("MenuName");

                    b.Property<string>("MenuNo");

                    b.Property<string>("MenuUrl");

                    b.Property<bool>("NoCache");

                    b.Property<string>("Order");

                    b.Property<string>("PMenuNo");

                    b.Property<int>("PlatformType");

                    b.Property<DateTime>("UpdateDateTime");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("DeepPath");

                    b.HasIndex("MenuNo")
                        .IsUnique();

                    b.HasIndex("PMenuNo");

                    b.ToTable("Zmn_Ac_Menus");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.RoleAggregate.Zmn_Ac_Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<string>("RoleDescr");

                    b.Property<string>("RoleName");

                    b.Property<DateTime>("UpdateDateTime");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("Zmn_Ac_Roles");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MenuNo");

                    b.Property<int>("PermissionType");

                    b.Property<int>("PlatformType");

                    b.Property<int?>("RoleId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Zmn_Ac_Permissions");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Pwd");

                    b.Property<string>("Sex");

                    b.Property<DateTime>("UpdateDateTime");

                    b.Property<int>("UpdateUserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Zmn_Ac_Users");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Zmn_Ac_UserRoles");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_Permission", b =>
                {
                    b.HasOne("AdminSystem.Domain.AggregatesModel.RoleAggregate.Zmn_Ac_Role", "Role")
                        .WithMany("PermissionList")
                        .HasForeignKey("RoleId");

                    b.HasOne("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_User", "ApplicationUser")
                        .WithMany("PermissionList")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_User", b =>
                {
                    b.OwnsOne("AdminSystem.Domain.AggregatesModel.UserAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("Zmn_Ac_UserId");

                            b1.Property<string>("City");

                            b1.Property<string>("Country");

                            b1.Property<string>("FullAddress");

                            b1.Property<string>("Province");

                            b1.Property<string>("Street");

                            b1.HasKey("Zmn_Ac_UserId");

                            b1.ToTable("Zmn_Ac_Users");

                            b1.HasOne("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_User")
                                .WithOne("Address")
                                .HasForeignKey("AdminSystem.Domain.AggregatesModel.UserAggregate.Address", "Zmn_Ac_UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_UserRole", b =>
                {
                    b.HasOne("AdminSystem.Domain.AggregatesModel.RoleAggregate.Zmn_Ac_Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AdminSystem.Domain.AggregatesModel.UserAggregate.Zmn_Ac_User", "ApplicationUser")
                        .WithMany("UserRoleList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
